### ISSUE TITLE
GP Service not running

### ISSUE THREAD

**Issue by nenge** [sirws/ThumbnailBuilderUI#12]
the GIS Server is not running currently:
http://nwdemo1.esri.com/arcgis/rest/services/GP/GenerateThumb/GPServer

"Could not access any GIS Server machines. Please contact your system administrator."

**Comment by sirws** [comment]
@nenge It should be up now.  You can also setup your own service by following the instructions here if it is mission critical: https://github.com/sirws/ThumbnailBuilderServer

Thanks!

**Comment by nenge** [comment]
Thanks Scott
I eventually found the link to build the gp service as it did not reveal itself on the current thumbnail generator github repository. May I suggest adding a link to the GP service builder repo from your thumbnail generator repo for those who wants to build their own server.

Also, if using Portal, can I use the same group finder to find the group IDs where I am putting the underlay and overlay images?

Nathan Enge
Esri Canada | 300-702 Fort St | Victoria BC V8W 1H2
T 250-410-0215 | esri.cahttp://esri.ca/
